"""
Bezubaan AI Service — Mock AI Provider

Deterministic mock provider for development and testing.
Returns fixed structured responses without calling any external API.

This provider is selected when AI_PROVIDER=mock (the default).
"""
import time

from app.schemas.triage import (
    TriageRequest,
    TriageResponse,
    ModelMetadata,
)
from app.providers.base import AIProvider


class MockProvider(AIProvider):
    """
    Deterministic mock AI provider.

    Returns realistic-looking but FIXED triage responses.
    Used for:
      - Local development without API keys
      - Unit/integration tests
      - Validating the NestJS ↔ AI service contract
    """

    async def analyze_rescue(self, request: TriageRequest) -> TriageResponse:
        start = time.monotonic()

        # Deterministic observations based on input content
        observations = [
            f"Rescue report received for location ({request.location.latitude}, {request.location.longitude}).",
            f"Reporter describes: '{request.description[:100]}...' (truncated for summary)."
            if len(request.description) > 100
            else f"Reporter describes: '{request.description}'.",
        ]

        if request.animal_info and request.animal_info.species:
            observations.append(
                f"Animal identified as species: {request.animal_info.species}."
            )

        if request.image_url:
            observations.append(
                "Image reference provided. (Mock provider does not perform actual image analysis.)"
            )

        severity = "Medium"  # Default mock severity
        if any(
            keyword in request.description.lower()
            for keyword in ["bleeding", "unconscious", "critical", "dying", "hit by"]
        ):
            severity = "High"
        elif any(
            keyword in request.description.lower()
            for keyword in ["minor", "small", "scratch", "healthy"]
        ):
            severity = "Low"

        elapsed_ms = int((time.monotonic() - start) * 1000)

        return TriageResponse(
            observations=observations,
            preliminary_assessment=(
                "Based on the provided description, the animal appears to need attention. "
                "This is a PRELIMINARY AI assessment and NOT a verified diagnosis."
            ),
            severity_estimate=severity,
            recommended_actions=[
                "Dispatch a volunteer to assess the situation on-site.",
                "Prepare transport to the nearest veterinary facility if injuries are confirmed.",
                "Notify the NGO admin for case review.",
            ],
            safety_warnings=[
                "Do not approach the animal if it appears aggressive or in severe distress.",
                "Wear protective gloves when handling injured animals.",
            ],
            confidence_note=(
                "This is a MOCK AI assessment generated for development/testing. "
                "In production, this would be generated by a real AI model. "
                "It is NOT a verified diagnosis and must be reviewed by a human."
            ),
            model_metadata=ModelMetadata(
                provider="mock",
                model="mock-triage-v1",
                processing_time_ms=elapsed_ms,
            ),
            correlation_id=request.correlation_id,
        )
